on:

  push:

    branches:

      - main



jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout app repository

        uses: actions/checkout@v3



      - name: Login to Docker Hub

        uses: docker/login-action@v2

        with:

          username: ${{ secrets.DOCKER_USERNAME }}

          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: Build and push Docker image

        uses: docker/build-push-action@v4

        with:

          context: .

          push: true

          tags: |
            guestivalet/app-fastapi:latest
            guestivalet/app-fastapi:${{ github.sha }}
- name: Checkout manifests repository
        uses: actions/checkout@v3
        with:
          repository: 'GuEstivalet/manifests-fastapi'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: manifests-fastap # Nome do diretório local

      # 6. Update Kubernetes manifest
      - name: Update Kubernetes manifest
        run: |
          # ENTRA NO DIRETÓRIO CORRETO (sem o 'i')
          cd manifests-fastap
          
          # Entra no subdiretório K8S e executa o SED
          cd k8s
          
          # Uso de aspas duplas e regex robusta para garantir a substituição
          sed -i "s|^[[:space:]]*image:.*|      image: guestivalet/app-fastapi:${{ github.sha }}|g" deployment.yaml

      # 7. Commit and push changes
      - name: Commit and push changes
        run: |
          # Entra no diretório clonado
          cd manifests-fastap
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # ADICIONA O ARQUIVO USANDO O CAMINHO RELATIVO COMPLETO (k8s/deployment.yaml)
          git add k8s/deployment.yaml
          
          # Verifica se houve alterações antes de commitar
          if ! git diff --cached --exit-code; then
            git commit -m "chore(manifests): Update image tag to ${{ github.sha }}"
            # Faz o push. O SSH-AGENT configurado antes permite isso.
            git push origin main
          else
            echo "No changes in deployment.yaml. Skipping commit/push."
          fi
